# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storybook

on:
  push:
    branches: [ storybook-implementation-vue ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Set config
        run: npm set registry=https://nexus.tools.services.qld.gov.au/nexus/repository/npm_all/ && npm set _auth=${{ secrets.NEXUS_TOKEN }}
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          STORYBOOK_ASSET_BASE=/qg-web-template npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: storybook-implementation-vue # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
